name = "get-editor-vip"
main = "worker.js"
compatibility_date = "2026-09-29"

# 只提供自定义域名，不额外暴露 *.workers.dev
workers_dev = false

# custom_domain = true：wrangler 会自动创建 DNS 记录与证书，不用手动加解析
routes = [
  { pattern = "get.editor.vip", custom_domain = true }
]
